spring:
  # 로그인 및 인증
  oauth2:
    kakao:
      client-id: "${spring.security.kakao.client-id}"
      client-secret: "${spring.security.kakao.client-secret}"
      url:
        redirect-uri: "${spring.security.kakao.url.redirect-uri}"

    naver:
      url:
        auth: "${spring.security.naver.url.auth}"
        api: "${spring.security.naver.url.api}"
        redirect-uri: "${spring.security.naver.url.redirect-uri}"
      client-id: "${spring.security.naver.client-id}"
      client-secret: "${spring.security.naver.client-secret}"

    jwt:
      secret-key: "${spring.security.jwt.secret-key}"

    accessToken:
      expirationSeconds: "${spring.security.accessToken.expirationSeconds}"

  profiles:
    active:
      - dev
    include:
      - secret
    jpa:
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          use_sql_comments: true