server:
  port: 8080

spring:
  profiles:
    active:
      - local
    include:
      - secret
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
  data:
    redis:
      host: redis
      port: 6379
  security:
    user:
      name: admin
      password: 1234