spring:
  security:
    user:
      name: admin
      password: 1234
  profiles:
    active:
      - dev
    include:
      - secret
  data:
    redis:
      host: db.tmdgjsdl1.site
      port: 6379
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

front:
  base_url: http://localhost:8080

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure.security: DEBUG
    org.springframework.security.oauth2: DEBUG
